[env:seeed-xiao-s3-custom]
extends = esp32s3_base
board = seeed-xiao-s3
board_level = pr
board_check = true
board_build.partitions = default_8MB.csv
upload_protocol = esptool
upload_speed = 921600
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
lib_deps =
  ${esp32s3_base.lib_deps}
build_unflags =
  ${esp32s3_base.build_unflags}
  -DARDUINO_USB_MODE=1
build_flags = 
  ${esp32s3_base.build_flags}
  -D SEEED_XIAO_S3
  -I variants/esp32s3/seeed_xiao_s3
  -DBOARD_HAS_PSRAM 
  -DARDUINO_USB_MODE=0
  ; User Preferences
  -DUSERPREFS_FIXED_BLUETOOTH=990099
  -DUSERPREFS_CONFIG_LORA_REGION=meshtastic_Config_LoRaConfig_RegionCode_EU_868
  ; Core feature exclusions
  -DMESHTASTIC_EXCLUDE_WIFI
  -DMESHTASTIC_EXCLUDE_ETHERNET
  -DMESHTASTIC_EXCLUDE_GPS
  -DMESHTASTIC_EXCLUDE_SCREEN
  -DMESHTASTIC_EXCLUDE_MQTT
  -DMESHTASTIC_EXCLUDE_TZ
  ; Optional module exclusions
  -DMESHTASTIC_EXCLUDE_AUDIO
  -DMESHTASTIC_EXCLUDE_DETECTIONSENSOR
  -DMESHTASTIC_EXCLUDE_ENVIRONMENTAL_SENSOR
  -DMESHTASTIC_EXCLUDE_HEALTH_TELEMETRY
  -DMESHTASTIC_EXCLUDE_EXTERNALNOTIFICATION
  -DMESHTASTIC_EXCLUDE_PAXCOUNTER
  -DMESHTASTIC_EXCLUDE_POWER_TELEMETRY
  -DMESHTASTIC_EXCLUDE_RANGETEST
  -DMESHTASTIC_EXCLUDE_REMOTEHARDWARE
  -DMESHTASTIC_EXCLUDE_ATAK
  -DMESHTASTIC_EXCLUDE_CANNEDMESSAGES
  -DMESHTASTIC_EXCLUDE_NEIGHBORINFO
  -DMESHTASTIC_EXCLUDE_WAYPOINT
  -DMESHTASTIC_EXCLUDE_INPUTBROKER
  -DMESHTASTIC_EXCLUDE_POWERSTRESS
