[env:seeed-xiao-s3-custom-roamer-admin]
;Device description: User device with remote node management (admin) privilege
extends = esp32s3_base
board = seeed-xiao-s3
board_level = pr
board_check = true
board_build.partitions = default_8MB.csv
upload_protocol = esptool
upload_speed = 921600
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
lib_deps =
  ${esp32s3_base.lib_deps}
build_unflags =
  ${esp32s3_base.build_unflags}
  -DARDUINO_USB_MODE=1
build_flags = 
  ${esp32s3_base.build_flags}
  -D SEEED_XIAO_S3
  -I variants/esp32s3/seeed_xiao_s3
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_MODE=0
  ; User Preferences
  -DUSERPREFS_FIXED_BLUETOOTH=990099
  -DUSERPREFS_CONFIG_LORA_REGION=meshtastic_Config_LoRaConfig_RegionCode_EU_868
  ; Admin Public Keys - Remote Node Management
  -DUSERPREFS_USE_ADMIN_KEY_0="{ 0x2c, 0x63, 0xce, 0x25, 0xfd, 0x81, 0x14, 0x10, 0xd3, 0xab, 0x62, 0xc0, 0x46, 0x1b, 0xc9, 0x13, 0xb0, 0x01, 0xd8, 0xc1, 0x21, 0xcf, 0xfc, 0x4f, 0x3d, 0xb2, 0xbe, 0xa5, 0xb9, 0x25, 0x1d, 0x76 }"
  -DUSERPREFS_USE_ADMIN_KEY_1="{ 0xfb, 0xc2, 0x05, 0x3e, 0x97, 0xe1, 0xe9, 0x89, 0x98, 0x60, 0x10, 0x11, 0xaa, 0xf0, 0xe0, 0xb0, 0x67, 0x02, 0x6a, 0x3d, 0x4e, 0xcf, 0xa0, 0x5d, 0x31, 0xf9, 0x49, 0x4c, 0xe1, 0x36, 0x8a, 0x5a }"
  -DUSERPREFS_USE_ADMIN_KEY_2="{ 0x97, 0x99, 0x92, 0x2f, 0xde, 0xf7, 0xf5, 0xe7, 0xbe, 0x67, 0x48, 0xfc, 0xae, 0x97, 0x32, 0xee, 0x62, 0xe6, 0x4e, 0xbc, 0x9c, 0x7f, 0x07, 0x95, 0x37, 0x1e, 0x90, 0xe2, 0x80, 0x86, 0xed, 0x7b }"
  ; Module exclusions
  -DMESHTASTIC_EXCLUDE_WIFI
  -DMESHTASTIC_EXCLUDE_ETHERNET
  -DMESHTASTIC_EXCLUDE_GPS
  -DMESHTASTIC_EXCLUDE_SCREEN
  -DMESHTASTIC_EXCLUDE_MQTT
  -DMESHTASTIC_EXCLUDE_TZ
  -DMESHTASTIC_EXCLUDE_AUDIO
  -DMESHTASTIC_EXCLUDE_DETECTIONSENSOR
  -DMESHTASTIC_EXCLUDE_ENVIRONMENTAL_SENSOR
  -DMESHTASTIC_EXCLUDE_HEALTH_TELEMETRY
  -DMESHTASTIC_EXCLUDE_EXTERNALNOTIFICATION
  -DMESHTASTIC_EXCLUDE_PAXCOUNTER
  -DMESHTASTIC_EXCLUDE_POWER_TELEMETRY
  -DMESHTASTIC_EXCLUDE_REMOTEHARDWARE
  -DMESHTASTIC_EXCLUDE_ATAK
  -DMESHTASTIC_EXCLUDE_CANNEDMESSAGES
  -DMESHTASTIC_EXCLUDE_NEIGHBORINFO
  -DMESHTASTIC_EXCLUDE_INPUTBROKER
  -DMESHTASTIC_EXCLUDE_POWERSTRESS
  -DMESHTASTIC_EXCLUDE_SERIAL
  -DMESHTASTIC_EXCLUDE_I2C
  -DDISABLE_NTP
  -DDISABLE_WELCOME_UNSET
